# Generated by Django 5.1 on 2025-06-20 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_note_content_alter_tag_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_tag',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='note.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='uncategorized', max_length=32, unique=True),
        ),
    ]
